/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-02-20 17:28:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class hosokham_002dchitiet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/Github/EclipseWorkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project%20v1.1/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1531452420000L));
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.5.jar", Long.valueOf(1548354033708L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("       \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/png\" href=\"assets/img/LogoTLU.png\"/>\r\n");
      out.write("    <title>Hệ thống quản lý sức khỏe</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS CDN -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css\" integrity=\"sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4\" crossorigin=\"anonymous\">\r\n");
      out.write("    <!-- Our Custom CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/style-menu.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/styles.css\">\r\n");
      out.write("    <!-- Scrollbar Custom CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome JS -->\r\n");
      out.write("    <script defer src=\"https://use.fontawesome.com/releases/v5.0.13/js/solid.js\" integrity=\"sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script defer src=\"https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js\" integrity=\"sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"https://use.fontawesome.com/releases/v5.0.6/css/all.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- Nucleo Icons -->\r\n");
      out.write("  <link href=\"assets/css/nucleo-icons.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <!-- CSS Files -->\r\n");
      out.write("  <!-- CSS Just for demo purpose, don't include it in your project -->\r\n");
      out.write("  <link href=\"assets/css/demo.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"d-block px-3 py-1 text-center text-bold text-white old-bv\"></div> \r\n");
      out.write("     <nav class=\"navbar navbar-expand-lg navbar-absolute navbar-transparent no-bg sticky-top  \">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <div class=\"navbar-wrapper\">\r\n");
      out.write("            <div class=\"navbar-toggle d-inline\">\r\n");
      out.write("              <button type=\"button\" class=\"navbar-toggler\">\r\n");
      out.write("                <span class=\"navbar-toggler-bar bar1\"></span>\r\n");
      out.write("                <span class=\"navbar-toggler-bar bar2\"></span>\r\n");
      out.write("                <span class=\"navbar-toggler-bar bar3\"></span>\r\n");
      out.write("              </button>\r\n");
      out.write("            </div>\r\n");
      out.write("             <button type=\"button\" id=\"sidebarCollapse\" class=\"btn more\">\r\n");
      out.write("                        <i class=\"fas fa fa-server\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("            <p class=\"navbar-brand\" href=\"#pablo\">Quản lý Giáo viên</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navigation\" aria-controls=\"navigation-index\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-bar navbar-kebab\"></span>\r\n");
      out.write("            <span class=\"navbar-toggler-bar navbar-kebab\"></span>\r\n");
      out.write("            <span class=\"navbar-toggler-bar navbar-kebab\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"navigation\">\r\n");
      out.write("            <ul class=\"navbar-nav ml-auto \">\r\n");
      out.write("\r\n");
      out.write("              <li class=\"dropdown nav-item\">\r\n");
      out.write("                <a href=\"#\" class=\"dropdown-toggle nav-link\" data-toggle=\"dropdown\">\r\n");
      out.write("                  <div class=\"photo\">\r\n");
      out.write("                    <img src=\"assets/img/anime3.png\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                 \r\n");
      out.write("                  <p class=\"d-lg-none\">\r\n");
      out.write("                    Log out\r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"dropdown-menu dropdown-navbar\">\r\n");
      out.write("                  <li class=\"nav-link\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-item dropdown-item\">Profile</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-link\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-item dropdown-item\">Settings</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                  <li class=\"nav-link\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-item dropdown-item\">Log out</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"separator d-lg-none\"></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("       \r\n");
      out.write("        <!-- Sidebar  -->\r\n");
      out.write("        <nav id=\"sidebar\">\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"sidebar-cover\">\r\n");
      out.write("            <div class=\"sidebar-header\">\r\n");
      out.write("                    <a href=\"\"><h3>Health care</h3></a> \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"list-unstyled components\">\r\n");
      out.write("                <p class=\"head-title\">Thăng Long University</p>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"trangchu.html\">Trang chủ</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li  >\r\n");
      out.write("                    <a href=\"khoa.html\">Quản lý Khoa</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                 <li>\r\n");
      out.write("                    <a href=\"bomon.html\">Quản lý Bộ Môn</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"active\">\r\n");
      out.write("                    <a href=\"giaovien.html\">Quản lý Giáo viên</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"kykham.html\">Quản lý Kỳ khám</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"hoso.html\">Quản lý Hồ sơ khám bệnh</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"loaibenh.html\">Quản lý Loại bệnh</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"benh.html\">Quản lý Bệnh</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"sucosuckhoe.html\">Quản lý Sự cố sức khỏe</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"giaoviencankham.html\">Quản lý giáo viên cần khám</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"thongke.html\">Thống kê báo cáo</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"list-unstyled CTAs\">\r\n");
      out.write("              <div>\r\n");
      out.write("                  <image src=\"assets/img/LogoTLU.png\" class=\"container-fluid mb-3 mt--2\"> </image>\r\n");
      out.write("               </div>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\" class=\"download\">Trợ giúp</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\" class=\"article\">Đội ngũ thiết kế</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- Page Content  -->\r\n");
      out.write("        <div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Main  --> \r\n");
      out.write("        <div class=\"\">\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("            <nav class=\"navbar topnav marb-10\">\r\n");
      out.write("              <form class=\"card-body card no-padding\" items=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" var=\"file\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group row no-margin\">\r\n");
      out.write("                  <div class=\"col-md-6\">\r\n");
      out.write("                  <label for=\"staticEmail\" class=\"col-md-4 col-form-label auto-w\">Họ tên :</label>\r\n");
      out.write("                  <input type=\"text\" readonly class=\" col-form-label auto-w no-margin\" id=\"staticEmail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-md-6\">\r\n");
      out.write("                  <label for=\"staticEmail\" class=\"col-md-4 col-form-label auto-w\">Mã hồ sơ :</label>\r\n");
      out.write("                  <input type=\"text\" readonly class=\" col-form-label auto-w no-margin\" id=\"staticEmail\" value=\"EF");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.examfileId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group row no-margin\">\r\n");
      out.write("                  <div class=\"col-md-6\">\r\n");
      out.write("                  <label for=\"staticEmail\" class=\"col-md-4 col-form-label auto-w\">Mã giáo viên :</label>\r\n");
      out.write("                  <input type=\"text\" readonly class=\" col-form-label auto-w no-margin\" id=\"staticEmail\" value=\"G");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-md-6\">\r\n");
      out.write("                  <label for=\"staticEmail\" class=\"col-md-4 col-form-label auto-w\">Ngày khám :</label>\r\n");
      out.write("                  <input type=\"date\" readonly class=\" col-form-label auto-w no-margin\" id=\"staticEmail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </form>\r\n");
      out.write("            </nav>\r\n");
      out.write("         <div class=\"line_20\"></div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg navbar-light bg-light topnav marb-10\">\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    <li class=\"nav-item list-item\">\r\n");
      out.write("                        <div class=\"dropdown show\">\r\n");
      out.write("                            <a class=\"btn btn-secondary dropdown-toggle\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                            Kỳ khám bệnh\r\n");
      out.write("                          </a>\r\n");
      out.write("\r\n");
      out.write("                          <div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuLink\">\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"#\">Kỳ khám bệnh 1</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"#\">Kỳ khám bệnh 2</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg navbar-light bg-light topnav marb-10\">\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"nav-item list-item\">\r\n");
      out.write("                        <a href=\"xetnghiemmau.html\">\r\n");
      out.write("                          <button type=\"button\" id=\"sidebarCollapse\" class=\"btn btn-danger\">\r\n");
      out.write("                                  <i class=\"fas fa fa-tint\"></i>\r\n");
      out.write("                                  <span>Hồ sơ Xét nghiệm máu cơ bản</span>\r\n");
      out.write("                          </button>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"nav-item list-item\">\r\n");
      out.write("                        <a href=\"sieuam.html\">\r\n");
      out.write("                          <button type=\"button\" id=\"sidebarCollapse\" class=\"btn btn-warning\">\r\n");
      out.write("                                  <i class=\"fas fa fa-assistive-listening-systems\"></i>\r\n");
      out.write("                                  <span>Hồ sơ Siêu âm</span>\r\n");
      out.write("                          </button>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"nav-item list-item\">\r\n");
      out.write("                        <a href=\"x-quang.html\">\r\n");
      out.write("                          <button type=\"button\" id=\"sidebarCollapse\" class=\"btn btn-info\">\r\n");
      out.write("                                  <i class=\"fas fa fa-user-circle\"></i>\r\n");
      out.write("                                  <span>Hồ sơ Chụp X-Quang phổi</span>\r\n");
      out.write("                          </button>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item list-item\"></li>\r\n");
      out.write("                    <li class=\"nav-item list-item\"></li>\r\n");
      out.write("                    <!--\r\n");
      out.write("                    <li class=\"nav-item list-item\">\r\n");
      out.write("                        <a href=\"khamnoi.html\">\r\n");
      out.write("                          <button type=\"button\" id=\"sidebarCollapse\" class=\"btn btn-success\">\r\n");
      out.write("                                  <i class=\"fas fa fa-street-view\"></i>\r\n");
      out.write("                                  <span>Hồ sơ Khám nội tổng quát</span>\r\n");
      out.write("                          </button>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    -->\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("            <form class=\"card-body card\" items=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" var=\"detail\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("              <div class=\"border-gray\">\r\n");
      out.write("                    <h5>Chỉ số sơ bản</h5>\r\n");
      out.write("                    <div class=\"line_20\"></div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"form-row\">\r\n");
      out.write("                    <div class=\"col-md-3 mb-4 mr-2\">\r\n");
      out.write("                        <label for=\"validationDefault01\">Mắt trái</label>\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                        <span class=\"input-group-text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.leftEye }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                     \t<div class=\"input-group-append\">\r\n");
      out.write("                        <span class=\"input-group-text\">/ 10</span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-3 mb-4\">\r\n");
      out.write("                        <label for=\"validationDefault01\">Mắt phải</label>\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                         <span class=\"input-group-text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.rightEye}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                        <span class=\"input-group-text\">/ 10</span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                 \r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"form-row\">\r\n");
      out.write("                    <div class=\"col-md-3 mb-4 mr-2\">\r\n");
      out.write("                        <label for=\"validationDefault01\">Chiều cao</label>\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                        <span class=\"input-group-text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.height}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                        <div class=\"input-group-append\">\r\n");
      out.write("                        <span class=\"input-group-text\">cm</span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-3 mb-4 mr-2\">\r\n");
      out.write("                        <label for=\"validationDefault01\">Cân nặng</label>\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                          <span class=\"input-group-text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.weight}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                          <div class=\"input-group-append\">\r\n");
      out.write("                        <span class=\"input-group-text\">kg</span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-3 mb-4\">\r\n");
      out.write("                        <label for=\"validationDefault01\">BMI</label>\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                          <span class=\"input-group-text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.BMI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                 \r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("             \r\n");
      out.write("                <div class=\"form-row\">\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"col-md-3 mb-2 mr-2\">\r\n");
      out.write("                        <label for=\"validationDefault01\">Mạch</label>\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                          <span class=\"input-group-text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.beat}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                          <div class=\"input-group-append\">\r\n");
      out.write("                        <span class=\"input-group-text\">lần/phút</span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 mb-2 mr-2\">\r\n");
      out.write("                        <label for=\"validationDefault01\">Huyết áp</label>\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                          <span class=\"input-group-text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.pressure}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                          <div class=\"input-group-append\">\r\n");
      out.write("                        <span class=\"input-group-text\">mmHg</span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                     <div class=\"col-md-4 mb-2\">\r\n");
      out.write("                        <label for=\"validationDefault01\">Phân loại thể lực</label>\r\n");
      out.write("                          <span class=\"input-group-text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.pclass}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-row\" items=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" var=\"file\">\r\n");
      out.write("                <div class=\"col-md-8 mb-3\">\r\n");
      out.write("                  <label for=\"validationDefault01\">Mô tả</label>\r\n");
      out.write("                  <span class=\"input-group-text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.descrip}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-row\">\r\n");
      out.write("                <div class=\"col-md-8 mb-3\">\r\n");
      out.write("                  <label for=\"validationDefault01\">Kết luận</label>\r\n");
      out.write("                  <span class=\"input-group-text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.conclude}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-row\">                   <!--    Set role for user    -->\r\n");
      out.write("                <div class=\"col-md-3 mb-3\">\r\n");
      out.write("                  <label for=\"inputState\">Trạng thái</label>      \r\n");
      out.write("                  <span class=\"input-group-text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                  </select>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("             <div class=\"line_20\"> </div>\r\n");
      out.write("            <a href=\"giaovien.html\"><button class=\"btn btn-default\" type=\"button\">Trở lại</button></a>\r\n");
      out.write("            <button class=\"btn btn-primary\" type=\"submit\">Lưu</button>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("             <!-- End Main  --> \r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery CDN - Slim version (=without AJAX) -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- Popper.JS -->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js\" integrity=\"sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js\" integrity=\"sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- jQuery Custom Scroller CDN -->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("            $(\"#sidebar\").mCustomScrollbar({\r\n");
      out.write("                theme: \"minimal\"\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            $('#sidebarCollapse').on('click', function () {\r\n");
      out.write("                $('#sidebar, #content').toggleClass('active');\r\n");
      out.write("                $('.collapse.in').toggleClass('in');\r\n");
      out.write("                $('a[aria-expanded=true]').attr('aria-expanded', 'false');\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
